export const PERIOD_TYPES: any[] = [
  { value: 'Monthly', name: 'Monthly', shown: false },
  { value: 'BiMonthly', name: 'BiMonthly', shown: false },
  { value: 'Quarterly', name: 'Quarterly', shown: false },
  { value: 'SixMonthly', name: 'Six-Monthly', shown: false },
  { value: 'SixMonthlyApril', name: 'Six-Monthly April', shown: true },
  { value: 'Yearly', name: 'Yearly', shown: false },
  { value: 'FinancialApril', name: 'Financial-April', shown: false },
  { value: 'FinancialJuly', name: 'Financial-July', shown: false },
  { value: 'FinancialOctober', name: 'Financial-October', shown: false },
  { value: 'RelativeWeek', name: 'Relative Week', shown: false },
  { value: 'RelativeMonth', name: 'Relative Month', shown: false },
  { value: 'RelativeBiMonth', name: 'Relative BiMonth', shown: false },
  { value: 'RelativeQuarter', name: 'Relative Quarter', shown: false },
  { value: 'RelativeYear', name: 'Relative Year', shown: false },
  {
    value: 'RelativeFinancialYear',
    name: 'Relative Financial Year',
    shown: false,
  },
];
